name: Deploy to cloudtype
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: jeonghwanmin/penple
          stage: main
          yaml: >
            name: penple-server

            app: node@18

            options:
              env:
                - name: DATABASE_URL
                  value:  ${{ secrets.DATABASE_URL }}
                - name: MAIL_HOST
                  value:  ${{ secrets.MAIL_HOST }}
                - name: MAIL_USER
                  value:  ${{ secrets.MAIL_USER }}
                - name: MAIL_PASSWORD
                  value:  ${{ secrets.MAIL_PASSWORD }}
                - name: MAIL_FROM
                  value:  ${{ secrets.MAIL_FROM }}
              ports: "8080"
              build: npm run build
              start: npm run start
              install: npm install --no-update-notifier
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: nest.js
